spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/free_ads_demo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 692391568024-lh3g3433suegam6g9s06ovfcc3sme36k.apps.googleusercontent.com
            clientSecret: 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